# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 491817baee701a04952fd9f8cc197603150571b9c0f25f5a438e0d2aadd157a06b5d569df0c9055490f668c0892d72e0b1d58baeb628d3f2a2f159eea1d81fc7

test:
  secret_key_base: 12024f2f06f6547d09190df06a59f85cc01213d672871cf98e1c6d761c3c7ec24905a3b7cbe479dd37f33a65b9700bdf6fd8648f68cbb95c6b05d7c9181d7730

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
